# Generated by Django 3.0.3 on 2020-03-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField()),
                ('description', models.TextField()),
                ('time_to_cook', models.CharField(blank=True, max_length=100, null=True)),
                ('ingredients', models.TextField()),
                ('prep_method', models.TextField()),
            ],
        ),
    ]
