# Generated by Django 3.0.3 on 2020-03-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='image',
        ),
        migrations.AddField(
            model_name='food',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
