# Generated by Django 3.0.3 on 2020-03-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20200312_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='card_type',
            field=models.CharField(choices=[('day', 'Recipes_of_the_day'), ('breakfast', 'BREAKFAST'), ('lunch', 'LUNCH'), ('dinner', 'DINNER')], default='day', max_length=100),
        ),
    ]
