# Generated by Django 3.0.3 on 2020-03-14 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_food_card_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='timestamp',
        ),
    ]
