# Generated by Django 3.0.3 on 2020-03-15 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_remove_food_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='contribution',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
